// Mocks generated by Mockito 5.4.4 from annotations
// in akscore/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:akscore/models/match.dart' as _i3;
import 'package:akscore/models/player.dart' as _i5;
import 'package:akscore/models/team.dart' as _i4;
import 'package:akscore/providers/matches_provider.dart' as _i6;
import 'package:akscore/providers/theme_provider.dart' as _i9;
import 'package:akscore/services/real_api_service.dart' as _i10;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeThemeData_0 extends _i1.SmartFake implements _i2.ThemeData {
  _FakeThemeData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeMatch_1 extends _i1.SmartFake implements _i3.Match {
  _FakeMatch_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeam_2 extends _i1.SmartFake implements _i4.Team {
  _FakeTeam_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayer_3 extends _i1.SmartFake implements _i5.Player {
  _FakePlayer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatchesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchesProvider extends _i1.Mock implements _i6.MatchesProvider {
  MockMatchesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Match> get liveMatches => (super.noSuchMethod(
        Invocation.getter(#liveMatches),
        returnValue: <_i3.Match>[],
      ) as List<_i3.Match>);

  @override
  List<_i3.Match> get todayMatches => (super.noSuchMethod(
        Invocation.getter(#todayMatches),
        returnValue: <_i3.Match>[],
      ) as List<_i3.Match>);

  @override
  List<_i3.Match> get favoriteMatches => (super.noSuchMethod(
        Invocation.getter(#favoriteMatches),
        returnValue: <_i3.Match>[],
      ) as List<_i3.Match>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> fetchLiveMatches() => (super.noSuchMethod(
        Invocation.method(
          #fetchLiveMatches,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchTodayMatches() => (super.noSuchMethod(
        Invocation.method(
          #fetchTodayMatches,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchFavoriteMatches() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavoriteMatches,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addToFavorites(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [matchId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFromFavorites(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [matchId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isFavorite(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [matchId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i9.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  _i2.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i2.ThemeData);

  @override
  _i2.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i2.ThemeData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void toggleTheme() => super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTheme(bool? isDark) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [isDark],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RealApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealApiService extends _i1.Mock implements _i10.RealApiService {
  MockRealApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.Match>> getLiveMatches() => (super.noSuchMethod(
        Invocation.method(
          #getLiveMatches,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Match>>.value(<_i3.Match>[]),
      ) as _i7.Future<List<_i3.Match>>);

  @override
  _i7.Future<List<_i3.Match>> getTodayMatches() => (super.noSuchMethod(
        Invocation.method(
          #getTodayMatches,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Match>>.value(<_i3.Match>[]),
      ) as _i7.Future<List<_i3.Match>>);

  @override
  _i7.Future<_i3.Match> getMatchDetails(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #getMatchDetails,
          [matchId],
        ),
        returnValue: _i7.Future<_i3.Match>.value(_FakeMatch_1(
          this,
          Invocation.method(
            #getMatchDetails,
            [matchId],
          ),
        )),
      ) as _i7.Future<_i3.Match>);

  @override
  _i7.Future<_i4.Team> getTeamDetails(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getTeamDetails,
          [teamId],
        ),
        returnValue: _i7.Future<_i4.Team>.value(_FakeTeam_2(
          this,
          Invocation.method(
            #getTeamDetails,
            [teamId],
          ),
        )),
      ) as _i7.Future<_i4.Team>);

  @override
  _i7.Future<_i5.Player> getPlayerDetails(String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerDetails,
          [playerId],
        ),
        returnValue: _i7.Future<_i5.Player>.value(_FakePlayer_3(
          this,
          Invocation.method(
            #getPlayerDetails,
            [playerId],
          ),
        )),
      ) as _i7.Future<_i5.Player>);
}
