name: akscore
description: "A comprehensive live score application built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: any
  font_awesome_flutter: any

  # State Management
  provider: any

  # HTTP & Networking
  http: any
  web_socket_channel: any

  # Image Caching
  cached_network_image: any

  # Loading Animations
  shimmer: any

  # Notifications
  flutter_local_notifications: any
  timezone: any

  # Local Storage
  shared_preferences: any

  # JSON Serialization
  json_annotation: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any

  # Utilities
  intl: any
  url_launcher: any

  # Logging
  logger: any
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Code Generation
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/ml/
