
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirF1O_zCA8X_ffJntN7tyMrzuRp9HYGA',
    appId: '1:675635083455:web:fd25fcd8b5a777b180ee0a',
    messagingSenderId: '675635083455',
    projectId: 'akscore-379b7',
    authDomain: 'akscore-379b7.firebaseapp.com',
    databaseURL: 'https://akscore-379b7-default-rtdb.firebaseio.com',
    storageBucket: 'akscore-379b7.firebasestorage.app',
    measurementId: 'G-LEQQXDMYLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVhWfazvKkm9G1zcgGC6zdCghngktAqY',
    appId: '1:675635083455:android:98eb717d24eaa67880ee0a',
    messagingSenderId: '675635083455',
    projectId: 'akscore-379b7',
    databaseURL: 'https://akscore-379b7-default-rtdb.firebaseio.com',
    storageBucket: 'akscore-379b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJlrt4aDeTVfB8udqrzOwdYMg4zC4zOQ',
    appId: '1:675635083455:ios:f1607454d816881480ee0a',
    messagingSenderId: '675635083455',
    projectId: 'akscore-379b7',
    databaseURL: 'https://akscore-379b7-default-rtdb.firebaseio.com',
    storageBucket: 'akscore-379b7.firebasestorage.app',
    iosBundleId: 'com.example.akscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJlrt4aDeTVfB8udqrzOwdYMg4zC4zOQ',
    appId: '1:675635083455:ios:f1607454d816881480ee0a',
    messagingSenderId: '675635083455',
    projectId: 'akscore-379b7',
    databaseURL: 'https://akscore-379b7-default-rtdb.firebaseio.com',
    storageBucket: 'akscore-379b7.firebasestorage.app',
    iosBundleId: 'com.example.akscore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDirF1O_zCA8X_ffJntN7tyMrzuRp9HYGA',
    appId: '1:675635083455:web:5458e57e12f8d5b080ee0a',
    messagingSenderId: '675635083455',
    projectId: 'akscore-379b7',
    authDomain: 'akscore-379b7.firebaseapp.com',
    databaseURL: 'https://akscore-379b7-default-rtdb.firebaseio.com',
    storageBucket: 'akscore-379b7.firebasestorage.app',
    measurementId: 'G-KZENM1MYEF',
  );

}