// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6PEM0WzY5ZL_dQutSlfQLHoRSEh8kMU',
    appId: '1:478688419579:web:96c4c2b80afd4cbffcda5e',
    messagingSenderId: '478688419579',
    projectId: 'my-football-app-12345',
    authDomain: 'my-football-app-12345.firebaseapp.com',
    storageBucket: 'my-football-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf1eMU6Drpc40iFxItTC5-W7rCY6y3JrE',
    appId: '1:478688419579:android:2fb4b25ae900659bfcda5e',
    messagingSenderId: '478688419579',
    projectId: 'my-football-app-12345',
    storageBucket: 'my-football-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ED-X8pWXdJk6zFM6ZTBQaJnb0jIt8HM',
    appId: '1:478688419579:ios:01515d5219c654dafcda5e',
    messagingSenderId: '478688419579',
    projectId: 'my-football-app-12345',
    storageBucket: 'my-football-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ED-X8pWXdJk6zFM6ZTBQaJnb0jIt8HM',
    appId: '1:478688419579:ios:01515d5219c654dafcda5e',
    messagingSenderId: '478688419579',
    projectId: 'my-football-app-12345',
    storageBucket: 'my-football-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk6PEM0WzY5ZL_dQutSlfQLHoRSEh8kMU',
    appId: '1:478688419579:web:2876544b93943118fcda5e',
    messagingSenderId: '478688419579',
    projectId: 'my-football-app-12345',
    authDomain: 'my-football-app-12345.firebaseapp.com',
    storageBucket: 'my-football-app-12345.firebasestorage.app',
  );
}
